development:
  adapter: postgresql
  database: shiningsea_development
  encoding: unicode
  pool: 5
  password: 

test:
  adapter: postgresql
  database: shiningsea_test
  pool: 5
  encoding: unicode
  pool: 5
  password: 

production:
  adapter: postgresql
  database: shiningsea_production
  encoding: unicode
  pool: 5
  password: 
